import type { RecentActivityItem } from "../../../../types/dashboard";

export const recentActivities: RecentActivityItem[] = [
  {
    id: "withdrawal-1",
    type: "Withdrawal",
    user: "Abdulrazeez Abdulyaniu",
    amount: "0.000343 USDT",
    date: "24th Nov, 2024",
    time: "12:12AM",
    status: "Completed",
  },
  {
    id: "deposit-1",
    type: "Deposit",
    user: "Abdulrazeez Abdulyaniu",
    amount: "31,300.000343 USDT",
    date: "24th Nov, 2024",
    time: "12:12AM",
    status: "Completed",
  },
  {
    id: "deposit-2",
    type: "Deposit",
    user: "Abdulrazeez Abdulyaniu",
    amount: "50,000.23 NGN",
    date: "24th Nov, 2024",
    time: "12:12AM",
    status: "Completed",
  },
  {
    id: "savings-1",
    type: "Savings",
    user: "Abdulrazeez Abdulyaniu",
    amount: "100.03 USDT",
    date: "24th Nov, 2024",
    time: "12:12AM",
    status: "Completed",
  },
  {
    id: "airtime-1",
    type: "Airtime",
    user: "Abdulrazeez Abdulyaniu",
    amount: "10.03 USDT",
    date: "24th Nov, 2024",
    time: "12:12AM",
    status: "Completed",
  },
  {
    id: "data-1",
    type: "Data Subscription",
    user: "Abdulrazeez Abdulyaniu",
    amount: "5.20 USDT",
    date: "24th Nov, 2024",
    time: "12:12AM",
    status: "Completed",
  },
  {
    id: "electricity-1",
    type: "Electricity",
    user: "Abdulrazeez Abdulyaniu",
    amount: "15.29 USDT",
    date: "24th Nov, 2024",
    time: "12:12AM",
    status: "Completed",
  },
  {
    id: "fiat-withdrawal-1",
    type: "Fiat Withdrawal",
    user: "Abdulrazeez Abdulyaniu",
    amount: "8.49 USDT",
    date: "24th Nov, 2024",
    time: "12:12AM",
    status: "Completed",
  },
];

